// Code generated by Slice Machine. DO NOT EDIT.

import Carousel from './Carousel/index.svelte';
import Hero from './Hero/index.svelte';
import Stack from './Stack/index.svelte';

export const components = {
	carousel: Carousel,
	hero: Hero,
	stack: Stack
};
