// Code generated by Slice Machine. DO NOT EDIT.

import Carousel from './Carousel/index.svelte';
import Contact from './Contact/index.svelte';
import Hero from './Hero/index.svelte';

export const components = {
	carousel: Carousel,
	contact: Contact,
	hero: Hero
};
